// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : Daneshgah_tehran
// Coding : 16bpp mode RGB565
// Source file : C:\Users\AmirMahdi\Desktop\SpiLcd_Stm32_newlib_ili9341\images\images\dt.png
// *****************************************************************************

#define Daneshgah_tehran_height 320
#define Daneshgah_tehran_width 240
#define Daneshgah_tehran_bpp 4

