// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : jihad
// Coding : 16bpp mode RGB565
// Source file : C:\Users\AmirMahdi\Desktop\SpiLcd_Stm32_newlib_ili9341\images\images\Untitled.png
// *****************************************************************************

#define jihad_height 320
#define jihad_width 240
#define jihad_bpp 4

