// *****************************************************************************
// File generated by STM32 Imager 1.0
// Image name : mypic
// Coding : 16bpp mode RGB565
// Source file : C:\Users\AmirMahdi\Desktop\SpiLcd_Stm32_newlib_ili9341\images\images\38235a6b-a64d-41ee-a314-fbf631bc009e.jpg
// *****************************************************************************

#define mypic_height 320
#define mypic_width 240
#define mypic_bpp 4
